name: Terraform-CD-Tests
on:
  workflow_dispatch:

jobs:
  Terraform-ValidationTests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Validate Terraform
        uses: docker://ghcr.io/github/super-linter:slim-v4
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          VALIDATE_TERRAFORM: true
          VALIDATE_TERRAFORM_TERRASCAN: true

  Terraform-CD-Tests:
    env:
      TF_IN_AUTOMATION: true
      TF_INPUT: false
      ARM_CLIENT_ID: ${{ secrets.SP_KOMPITA_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.SP_KOMPITA_SEC }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.SP_KOMPITA_SUB }}
      ARM_TENANT_ID: ${{ secrets.SP_KOMPITA_TEN }}
    needs: Terraform-ValidationTests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1.2.1
        

      - name: Terraform Init
        id: init
        run: terraform init -no-color
        working-directory: Terraform

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve -no-color
        working-directory: Terraform
